{
    "openapi": "3.0.1",
    "info": {
        "title": "Freelancer Billing API",
        "description": "API to access info, bills and even submit timesheets through API",
        "version": "1"
    },
    "servers": [
        {
            "url": "https://billing.thevikas.com/api"
        }
    ],
    "security": [
        {
            "bearerAuth": []
        }
    ],
    "paths": {
        "/now/last": {
            "description": "To get last time entry",
            "get": {
                "tags": [
                    "last"
                ],
                "summary": "To just return data of currently running task and times",
                "operationId": "last",
                "responses": {
                    "200": {
                        "description": "N/a",
                        "content": {
                            "application/json; charset=utf-8": {
                                "schema": {
                                    "type": "object",
                                    "required": [
                                        "last"
                                    ],
                                    "properties": {
                                        "last": {
                                            "type": "string",
                                            "description": "Last time entry"
                                        }
                                    },
                                    "example": {
                                        "last": "2024-02-28 11:58"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "last"
                ],
                "summary": "To post last time entry again",
                "operationId": "last",
                "responses": {
                    "200": {
                        "description": "N/a",
                        "content": {
                            "application/json; charset=utf-8": {
                                "schema": {
                                    "type": "object",
                                    "required": [
                                        "last"
                                    ],
                                    "properties": {
                                        "last": {
                                            "type": "string",
                                            "description": "Last time entry"
                                        }
                                    },
                                    "example": {
                                        "last": "2024-02-28 11:58"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/now": {
            "description": "To get current time",
            "get": {
                "tags": [
                    "now"
                ],
                "summary": "To get current time",
                "operationId": "now",
                "responses": {
                    "200": {
                        "description": "N/a",
                        "content": {
                            "application/json; charset=utf-8": {
                                "schema": {
                                    "type": "object",
                                    "required": [
                                        "now"
                                    ],
                                    "properties": {
                                        "now": {
                                            "type": "string",
                                            "description": "Current time"
                                        }
                                    },
                                    "example": {
                                        "now": "2024-02-28 11:58"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "now"
                ],
                "summary": "To post a raw gtimelog string",
                "operationId": "now",
                "responses": {
                    "200": {
                        "description": "N/a",
                        "content": {
                            "application/json; charset=utf-8": {
                                "schema": {
                                    "type": "object",
                                    "required": [
                                        "now"
                                    ],
                                    "properties": {
                                        "now": {
                                            "type": "string",
                                            "description": "Current time"
                                        }
                                    },
                                    "example": {
                                        "now": "2024-02-28 11:58"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/projects/{NNN}": {
            "description": "To register users from API",
            "get": {
                "tags": [
                    "projects"
                ],
                "summary": "To get summary info of a project",
                "operationId": "projects",
                "parameters": [
                    {
                        "in": "path",
                        "name": "NNN",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "description": "Project name"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "N/a",
                        "content": {
                            "application/json; charset=utf-8": {
                                "schema": {
                                    "$ref": "#/components/schemas/ProjectRes"
                                },
                                "examples": {
                                    "good": {
                                        "summary": "when all was good",
                                        "value": {
                                            "Dated": "2024-02-28 11:58",
                                            "EstimatedIncome": 8064,
                                            "EstimatedTotalHours": 11.52,
                                            "Income": 7525,
                                            "Total": 10.75,
                                            "name": "xx1"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/projects": {
            "description": "To register users from API",
            "get": {
                "tags": [
                    "projects"
                ],
                "summary": "To get summary info of all projects",
                "operationId": "projects",
                "parameters": [
                    {
                        "in": "query",
                        "name": "page",
                        "schema": {
                            "type": "number"
                        },
                        "description": "N/a"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "N/a",
                        "content": {
                            "application/json; charset=utf-8": {
                                "schema": {
                                    "$ref": "#/components/schemas/ProjectsRes"
                                },
                                "examples": {
                                    "good": {
                                        "summary": "when all was good",
                                        "value": {
                                            "xx1": {
                                                "Dated": "2024-02-28 11:58",
                                                "EstimatedIncome": 8064,
                                                "EstimatedTotalHours": 11.52,
                                                "Income": 7525,
                                                "Total": 10.75,
                                                "name": "xx1"
                                            },
                                            "xx2": {
                                                "Dated": "2024-02-28 13:21",
                                                "EstimatedIncome": 231539,
                                                "EstimatedIncomeUSD": 2858.5,
                                                "EstimatedTotalHours": 114.34,
                                                "Income": 216101,
                                                "IncomeUSD": 2667.9166666666665,
                                                "Total": 106.71666666666667,
                                                "name": "xx2"
                                            },
                                            "summary": {
                                                "Total": 184,
                                                "Billable": 152,
                                                "EstimatedIncome": 330339,
                                                "Income": 308312,
                                                "Productivity": "83%",
                                                "EarningDays": "100%",
                                                "EffectiveHourlyRateINR": 2024,
                                                "ThisMonthHourlyRateINR": 1927
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "description": "API Token header",
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": ""
            }
        },
        "schemas": {
            "RecentTask": {
                "type": "object",
                "required": [
                    "task",
                    "last_time"
                ],
                "properties": {
                    "task": {
                        "type": "string",
                        "description": "Task name"
                    },
                    "last_time": {
                        "type": "string",
                        "description": "Last time entry"
                    }
                },
                "example": {
                    "task": "meeting",
                    "last_time": "2024-03-15 10:52"
                }
            },
            "Project": {
                "type": "object",
                "required": [
                    "name",
                    "Dated",
                    "EstimatedIncome",
                    "EstimatedTotalHours",
                    "Income",
                    "Total"
                ],
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "Project name"
                    },
                    "Dated": {
                        "type": "string",
                        "description": "Last time entry"
                    },
                    "EstimatedIncome": {
                        "type": "integer",
                        "description": "Estimated income"
                    },
                    "EstimatedTotalHours": {
                        "type": "number",
                        "description": "Estimated total hours"
                    },
                    "Income": {
                        "type": "integer",
                        "description": "Income"
                    },
                    "Total": {
                        "type": "number",
                        "description": "Total hours"
                    },
                    "recent": {
                        "type": "array",
                        "$ref": "#/components/schemas/RecentTask"
                    }
                }
            },
            "ProjectsRes": {
                "type": "object",
                "description": "Project data",
                "additionalProperties": {
                    "$ref": "#/components/schemas/Project"
                },
                "example": {
                    "axxxxxx": {
                        "Dated": "2024-03-15 10:20",
                        "EstimatedIncome": 100683,
                        "EstimatedIncomeUSD": 1243,
                        "EstimatedTotalHours": 49.72,
                        "Income": 53696,
                        "IncomeUSD": 662.9166666666666,
                        "Total": 26.516666666666666,
                        "name": "axxxxxx"
                    },
                    "pxxxxxx": {
                        "Dated": "2024-03-15 10:48",
                        "EstimatedIncome": 1708,
                        "EstimatedTotalHours": 2.44,
                        "Income": 910,
                        "Total": 1.3,
                        "name": "pxxxxxx"
                    },
                    "summary": {
                        "Billable": 62,
                        "Dated": "2024-03-16 16:26:40",
                        "EarningDays": "78%",
                        "EffectiveHourlyRateINR": 2219,
                        "EstimatedIncome": 256696,
                        "EstimatedTotalHours": 115.66,
                        "Income": 136902,
                        "Productivity": "70%",
                        "ThisMonthHourlyRateINR": 856,
                        "Total": 88,
                        "name": "Summary"
                    },
                    "wxxxxxx": {
                        "Dated": "1970-01-01 05:30",
                        "EstimatedIncome": 154305,
                        "EstimatedIncomeUSD": 1905,
                        "EstimatedTotalHours": 63.5,
                        "Income": 82296,
                        "IncomeUSD": 1016,
                        "Total": 33.86666666666667,
                        "name": "wxxxxxx",
                        "recent": {}
                    }
                }
            },
            "Task": {
                "type": "object",
                "required": [
                    "name",
                    "last_time",
                    "total",
                    "project"
                ],
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "Task name"
                    },
                    "last_time": {
                        "type": "string",
                        "description": "Last time entry"
                    },
                    "total": {
                        "type": "string",
                        "description": "Total time in minutes for the whole current month"
                    },
                    "project": {
                        "type": "string",
                        "description": "Project name"
                    }
                },
                "example": {
                    "name": "bogus",
                    "last_time": "2024-02-28 11:58",
                    "total": "0",
                    "project": "bogus"
                }
            },
            "TaskTimeStamp": {
                "type": "object",
                "required": [
                    "last_time",
                    "task",
                    "duration",
                    "status"
                ],
                "properties": {
                    "last_time": {
                        "type": "integer",
                        "description": "Time stamp"
                    },
                    "task": {
                        "type": "string"
                    },
                    "duration": {
                        "type": "integer",
                        "description": "Duration of this time entry"
                    },
                    "status": {
                        "type": "string",
                        "description": "Status of this time entry",
                        "enum": [
                            "running",
                            "paused",
                            "stopped"
                        ]
                    }
                }
            },
            "HomeRes": {
                "type": "object",
                "required": [
                    "first_page_url",
                    "to",
                    "from",
                    "total",
                    "current_page",
                    "last_page",
                    "status",
                    "dataflow",
                    "message",
                    "response"
                ],
                "properties": {
                    "status": {
                        "type": "integer",
                        "description": "Status code"
                    },
                    "message": {
                        "type": "string",
                        "description": "Response message"
                    },
                    "response": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/Product"
                        },
                        "description": "Product data"
                    },
                    "first_page_url": {
                        "type": "string",
                        "format": "uri",
                        "description": "URL of the first page of results"
                    },
                    "next_page_url": {
                        "description": "URL of the next page of results (can be NULL)"
                    },
                    "to": {
                        "type": "integer",
                        "description": "Number of records shown 'to'"
                    },
                    "from": {
                        "type": "integer",
                        "description": "Number of records shown 'from'"
                    },
                    "total": {
                        "type": "integer",
                        "description": "Total number of records"
                    },
                    "current_page": {
                        "type": "integer",
                        "description": "Current page number"
                    },
                    "last_page": {
                        "type": "integer",
                        "description": "Last page number"
                    },
                    "dataflow": {
                        "type": "integer",
                        "description": "Data flow value"
                    }
                },
                "example": {
                    "first_page_url": "https://bogus.com/api/webservice/home?page=1",
                    "next_page_url": null,
                    "to": 10,
                    "from": 1,
                    "total": 18,
                    "current_page": 1,
                    "last_page": 2,
                    "status": 1,
                    "dataflow": 0,
                    "message": "success",
                    "response": [
                        {
                            "id": 1,
                            "name": "bogus Diamond Thingi",
                            "price": "636.00",
                            "image": "https://bogus.com/img/1679050312.IMG_0080 march 13.jpg",
                            "try_on_product_id": null,
                            "wishlist": 0,
                            "vendor_id": 2,
                            "category_id": 107,
                            "stone_type": 1,
                            "product_preference": 2,
                            "top_category": 0,
                            "featured_status": 0,
                            "product_link": "https://bogus.com/vendor/product_detail/MTY="
                        }
                    ]
                }
            }
        }
    }
}